### ISSUE TITLE
Install, nothing worked

### ISSUE THREAD

**Issue by XinyueZ** [gabrielchua/RAGxplorer#4]
```
When ran 

pip install -r xxxxxx

nothing worked:

ERROR: Could not find a version that satisfies the requirement pysqlite3-binary (from versions: none)
ERROR: No matching distribution found for pysqlite3-binary
```

**Comment by gabrielchua** [comment]
Ah - my bad.

I realised this repo is specifically for deployment on streamlit's free hosting.

Can you try:
1. Removing `pysqlite3-binary` in the `requirements.txt`
2. Commenting out lines 5 to 7 in `app.py`:

```python
__import__('pysqlite3')
import sys
sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
```

**Comment by Mike92988** [comment]
Having a similar issue trying to run this on a codespace. commeneted out lines as described but seeing this in the output when running `streamlit run app.py`

```
Traceback (most recent call last):
File "/workspaces/RAGxplorer/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
exec(code, module.dict)
File "/workspaces/RAGxplorer/app.py", line 15, in <module>
from utils.rag import ...
File "/workspaces/RAGxplorer/utils/rag.py", line 6, in <module>
import chromadb
File "/workspaces/RAGxplorer/venv/lib/python3.10/site-packages/chromadb/init.py", line 79, in <module>
raise RuntimeError("Your system has an unsupported version of sqlite3. ChromaDB requires sqlite3 >= 3.35.0.")
RuntimeError: Your system has an unsupported version of sqlite3. ChromaDB requires sqlite3 >= 3.35.0.
```

**Comment by gabrielchua** [comment]
Hi @Mike92988  - could you run the following & share the results?


**in the terminal:**
> pip freeze

**In python:**
> import sqlite3
> sqlite3.version
